name: 'four_mile_analytics_sample'
version: 0.1.0

require-dbt-version: ">=0.18.0"
config-version: 2

# Configure database connection profile for dbt to use
profile: '4_mile_bq_sample'

# Set paths for dbt objects
analysis-paths: ["analysis"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
source-paths: ["models"]
test-paths: ["tests"]

log-path: "logs"
modules-path: "dbt_modules"
target-path: "target"
clean-targets:
    - "dbt_modules"
    - "target"

# Set query behavior: prepend comments and quoting
query-comment: "{{ query_comment(node) }}"
quoting:
  database: false
  schema: false
  identifier: false

on-run-start:
  - '{% do adapter.create_schema(api.Relation.create(target.project, "audit")) %}'
  - "{{ dbt_ml.create_model_audit_table() }}"


# DBT MODELS
models:
    four_mile_analytics_sample:
        +enabled: true
        +materialized: view
        +persist_docs:
            relation: true
            columns: true
        
        staging:
            +enabled: true
        
        marts:
            +enabled: true
            +materialized: table

            core:
                +schema: core
            product:
                +schema: product    
        
        ml:
            +enabled: true
            +schema: ml
            +materialized: model
            +post-hook: "{{ dbt_ml.model_audit() }}"


# Create scoped variables
vars:
    "dbt_date:time_zone": 'America/Los_Angeles'
    "dbt_ml:audit_schema": 'audit'
    "dbt_ml:audit_table": 'ml_models'

    four_mile_analytics_sample:
        source_database: 'four-mile-lake'
        analysis_start_date: '2016-01-01'
        dbt_project_created_date: '2020-11-19'  # Set as date when dbt project first created

    asana_source:
        asana_database: 'four-mile-lake'
    github_source:
        github_database: 'four-mile-lake'
    fivetran_log:
        fivetran_log_database: 'four-mile-lake'
        fivetran_log_schema: 'logs_fivetran'


# Define dbt data seeds
seeds:
    four_mile_analytics_sample:
      +enabled: true
