dbtVersion: 0.18.1

jobs:
# Unique list of schedule-based jobs to be orchestrated by Fivetran
 - name: daily_5am
   schedule: 0 13 * * *
   steps:
     - name: run all models
       command: dbt run
     - name: test all models
       command: dbt test
